### ISSUE TITLE
Thumbnail on main page link to another page or add preview text field?

### ISSUE THREAD

**Issue by ghost** [nunopress/kirby-themes-phantom#2]
Hey there,

The thumbnails on the main page link to a page named .../home/xx.
When I edit the page xx with a lot of text it features this text also in the thumbnails on the main page (see screenshot attached)
![screen shot 2016-10-14 at 15 14 43](https://cloud.githubusercontent.com/assets/22838515/19388662/080eb728-9221-11e6-9a0c-593ef8774f25.png)
. 

Is there a possibility to either
- link the thumbnail to another page like .../xyz instead of .../home/xx or
- add a field to edit this 'preview' text instead of displaying ALL the text of the page .../xx

I hope you understand what I mean.

Thanks for your work, keep up the good work.

All the best.
jagaland

**Comment by nunocodex** [comment]
@jagaland nice to meet you again, so yes this a problem (I don't think when I develop the porting).
I think the best way is use a new field for the titles in the home text and another one for the page, give me a time to comeback to office and I working on it.
Thanks for this suggestion/bug.

**Comment by nunocodex** [comment]
Ah for add to another page I need to change more code inside because at moment the home page read all children pages and transform to titles.

**Comment by nunocodex** [comment]
@jagaland Fixed here: https://github.com/nunopress/kirby-themes-phantom/releases/latest

Thanks.

**Comment by nunocodex** [comment]
@jagaland based on your request (and it's a good idea btw) I refactoring the home page with stucture fields for make more flexible based on requests. You can connect one tile to another page with page link, in my example you can make some tiles inside a invisible folder, with this method you can leave out of the menu all tiles and show the tiles in the home page.
In the structure fields you need to write title, cover, style and text then connect to a page link you choose.

I think now you are happy for this modifications 👍 

Send a new issue if you need help.

**Comment by ghost** [comment]
This looks promising, thanks. I'll check it out asap. :)
